# For Cloudflare Pages with Functions
name = "your-project-name"
compatibility_date = "2024-03-25"
pages_build_output_dir = "dist"  # Your build output directory

[build]
command = "npm run build"  # Your build command
upload.dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "anime_database"
database_id = "757ff463-027b-44f7-a456-75da8deb94af"
