name = "anime-watch-count"
main = "workers/anime-watch-count.js"
type = "javascript"
compatibility_date = "2025-03-13"

account_id = "b28649ce82eac859f113666c482934e9"
workers_dev = true

[[kv_namespaces]]
binding = "MY_KV"
id = "a1922f7dbe90435ea54837d383d9aae9"
preview_id = "a1922f7dbe90435ea54837d383d9aae9"  # <- Ini penting buat testing
